/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crud;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhorman Gonzalez << Jhorman967@gmail.com >>
 */
public class NotasEstudiante extends javax.swing.JFrame {
    DataBase cc = new DataBase();
    Connection con = cc.Conexion();

    /** Creates new form Notas */
    public NotasEstudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.ShowNotas();
    }
 public void ShowNotas() {
        
        int cont = 0;
        
        DefaultTableModel modelo = new DefaultTableModel();
                 modelo.addColumn("Id");
                 modelo.addColumn("Nombre");
                 TableSocialesEstu.setModel(modelo);
        try {
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM logro_sociales");
             while (rs.next()){
                 modelo.addColumn(rs.getString(2));
                 TableSocialesEstu.setModel(modelo);
                 cont++;
             }
             
           cont = cont + 2;  
            
         String [] datos = new String [cont];    
         
            try {
                 Statement st2 = con.createStatement();
                 ResultSet rs2 = st.executeQuery("SELECT * FROM sociales");
                 
                 while (rs2.next()){
                     int j = 1;
                     for (int i = 0; i<cont; i++ ) {
                         
                      datos[i]=rs2.getString(j);
                       j++;
                       
                     }    
                  modelo.addRow(datos);
                  
                 }
                 
                 TableSocialesEstu.setModel(modelo);
            } catch (Exception e) {
            }
             
        } catch (Exception e) {
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        Sociales = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableSocialesEstu = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        Ingles = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableSocialesPro2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        Matematicas = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TableSocialesPro3 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        Quimica = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TableSocialesPro4 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        Tecnologia = new javax.swing.JPanel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        TableSocialesPro5 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        Español = new javax.swing.JPanel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        TableSocialesPro6 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LblNombreEstudiante = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtLogOut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 4, true));
        jTabbedPane4.setForeground(new java.awt.Color(34, 87, 122));
        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane4.setToolTipText("");
        jTabbedPane4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTabbedPane4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        Sociales.setBackground(new java.awt.Color(87, 204, 153));
        Sociales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Sociales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel11.setBackground(new java.awt.Color(34, 87, 122));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesEstu.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane6.setViewportView(TableSocialesEstu);
        if (TableSocialesEstu.getColumnModel().getColumnCount() > 0) {
            TableSocialesEstu.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel11.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel11.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane5.addTab("Planilla", jPanel11);

        Sociales.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("SOCIALES                 ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Sociales); // NOI18N

        Ingles.setBackground(new java.awt.Color(87, 204, 153));
        Ingles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Ingles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane6.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane6.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel14.setBackground(new java.awt.Color(34, 87, 122));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesPro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Actividad 1", "Actividad 2", "Actividad 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSocialesPro2.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane8.setViewportView(TableSocialesPro2);
        if (TableSocialesPro2.getColumnModel().getColumnCount() > 0) {
            TableSocialesPro2.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel14.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusable(false);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel14.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane6.addTab("Planilla", jPanel14);

        Ingles.add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("INGLES                      ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Ingles); // NOI18N

        Matematicas.setBackground(new java.awt.Color(87, 204, 153));
        Matematicas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Matematicas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane7.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane7.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel16.setBackground(new java.awt.Color(34, 87, 122));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesPro3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Actividad 1", "Actividad 2", "Actividad 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSocialesPro3.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane10.setViewportView(TableSocialesPro3);
        if (TableSocialesPro3.getColumnModel().getColumnCount() > 0) {
            TableSocialesPro3.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel16.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusable(false);
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel16.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane7.addTab("Planilla", jPanel16);

        Matematicas.add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("MATEMATICAS         ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Matematicas); // NOI18N

        Quimica.setBackground(new java.awt.Color(87, 204, 153));
        Quimica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Quimica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane8.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane8.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel18.setBackground(new java.awt.Color(34, 87, 122));
        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesPro4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Actividad 1", "Actividad 2", "Actividad 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSocialesPro4.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane12.setViewportView(TableSocialesPro4);
        if (TableSocialesPro4.getColumnModel().getColumnCount() > 0) {
            TableSocialesPro4.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel18.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusable(false);
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel18.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane8.addTab("Planilla", jPanel18);

        Quimica.add(jTabbedPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("QUIMICA                   ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Quimica); // NOI18N

        Tecnologia.setBackground(new java.awt.Color(87, 204, 153));
        Tecnologia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Tecnologia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane9.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane9.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel20.setBackground(new java.awt.Color(34, 87, 122));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesPro5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Actividad 1", "Actividad 2", "Actividad 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSocialesPro5.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane14.setViewportView(TableSocialesPro5);
        if (TableSocialesPro5.getColumnModel().getColumnCount() > 0) {
            TableSocialesPro5.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel20.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusable(false);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel20.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane9.addTab("Planilla", jPanel20);

        Tecnologia.add(jTabbedPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("TECNOLOGIA             ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Tecnologia); // NOI18N

        Español.setBackground(new java.awt.Color(87, 204, 153));
        Español.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 87, 122)));
        Español.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane10.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane10.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel22.setBackground(new java.awt.Color(34, 87, 122));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 237, 153), 3, true));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSocialesPro6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Actividad 1", "Actividad 2", "Actividad 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSocialesPro6.setGridColor(new java.awt.Color(56, 163, 165));
        jScrollPane16.setViewportView(TableSocialesPro6);
        if (TableSocialesPro6.getColumnModel().getColumnCount() > 0) {
            TableSocialesPro6.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel22.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 742, 100));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusable(false);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshMedium.png"))); // NOI18N
        jPanel22.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jTabbedPane10.addTab("Planilla", jPanel22);

        Español.add(jTabbedPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 790));

        jTabbedPane4.addTab("ESPAÑOL                    ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icono Estudio.png")), Español); // NOI18N

        Fondo.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1210, 760));

        jPanel1.setBackground(new java.awt.Color(34, 87, 122));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 237, 153), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AvatarEStudiante.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 110));

        LblNombreEstudiante.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LblNombreEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        LblNombreEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNombreEstudiante.setText("Nombre Estudiante");
        jPanel1.add(LblNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoBlanco.png"))); // NOI18N
        Fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 130, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("\"Educar es redimir\"");
        Fondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 380, 70));

        BtLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        BtLogOut.setToolTipText("");
        BtLogOut.setBorderPainted(false);
        BtLogOut.setContentAreaFilled(false);
        BtLogOut.setDefaultCapable(false);
        BtLogOut.setFocusable(false);
        BtLogOut.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        BtLogOut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-outMEdium.png"))); // NOI18N
        BtLogOut.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtLogOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLogOutActionPerformed(evt);
            }
        });
        Fondo.add(BtLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 50, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo Notas.jpg"))); // NOI18N
        Fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -1570, 1260, 2540));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLogOutActionPerformed
        Login X = new Login();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotasEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtLogOut;
    private javax.swing.JPanel Español;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Ingles;
    public static javax.swing.JLabel LblNombreEstudiante;
    private javax.swing.JPanel Matematicas;
    private javax.swing.JPanel Quimica;
    private javax.swing.JPanel Sociales;
    private javax.swing.JTable TableSocialesEstu;
    private javax.swing.JTable TableSocialesPro2;
    private javax.swing.JTable TableSocialesPro3;
    private javax.swing.JTable TableSocialesPro4;
    private javax.swing.JTable TableSocialesPro5;
    private javax.swing.JTable TableSocialesPro6;
    private javax.swing.JPanel Tecnologia;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    // End of variables declaration//GEN-END:variables

}
